import {ThemeContextProvider} from "@/app/providers";
import {AUTHOR} from "@/data";
import {geistMono, geistSans} from "@/theme/fonts";
import type {Metadata} from "next";
import "./globals.css";
import type {ReactNode} from "react";

export const metadata: Metadata = {
  title: "Create Next App with Docker",
  description: "Generated by create next app, with Docker",
  authors: [{name: AUTHOR.name, url: AUTHOR.website,}],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <ThemeContextProvider>
      {children}
    </ThemeContextProvider>
    </body>
    </html>
  );
}
